mysql_string: "login:password@tcp(adres_bazy:port_polaczenia)/nazwa_bazy?parseTime=true"
cron_line: "0 0 6,12,18 * *"
giveaway_time_string: "6:00, 12:00, 18:00"
system_token: "token bota"
csrv_secret: "secret api od kodow"
